### ISSUE TITLE
Is it Possible to Add 'Value' Property to Item

### ISSUE THREAD

**Issue by buzkanlamaca** [balachuang/DualSelectList#3]
Hi,
In my project, items also have id numbers. Users can see only item names but i work with item's id numbers. So is it possible to add Value property to your DualSelectList? For example:

'candidateItems' : [{"id":1,"text":"Item 1"}, {"id":2,"text":"Item 2"}] ...

**Comment by Martin-Labenne** [comment]
Try this : 
```
this.setCandidate = function (candidate) {
  for (var n=0; n<candidate.length; ++n) {
    if ( typeof candidate[n] === "object") {
      var itemKey = $.trim(candidate[n].key.toString());
      var itemString = $.trim(candidate[n].value.toString());
      if (itemString == '') continue;
        thisLftPanel.append('<div class="dsl-panel-item" data-key="'+ itemKey + '">' + itemString + '</div>');
      } else {
        var itemString = $.trim(candidate[n].toString());
        if (itemString == '') continue;
        thisLftPanel.append('<div class="dsl-panel-item">' + itemString + '</div>');
     }
   }
 };
```
Idem for `this.setSelection`

**Comment by balachuang** [comment]
I have added a new feature for this requirement. You can now use either pure String array or JSON Object Array as input. You can also determine the return value of  getSelection() function as String only or Full Object Array. Please see the latest code for detail.
