### ISSUE TITLE
Adding all resultats corresponds to a filtre in one click

### ISSUE THREAD

**Issue by PierreClementCazon** [balachuang/DualSelectList#4]
Thank you very much for this module !
Could you add the possibility of adding all results corresponds to a filter ?

**Comment by balachuang** [comment]
Since "Filter" is only the function of the demo HTML but not the function of this jQuery Plugin, I can create a button to add all filtered items to selection, but that will make no change to the plugin itself.

**Comment by balachuang** [comment]
I've added a new function to add all items to another panel by clicking the Triangle icon in the filter input. When there is no filter, this function will move all items in the panel; when there is filter, this function will move all filtered items in the panel.
