### ISSUE TITLE
Multiple DualSelects

### ISSUE THREAD

**Issue by ace540i** [balachuang/DualSelectList#5]
Thank you for a great tool!    
i have added two Dual Selectors to one web page. everything works ok except the drag and drop. 
i think it's having a problem with the class names and not knowing which left panel to put the Items into. 
do you know if i can use two DualSelect controls on one page.  each one needs to function independently.
can i use an id or dif class names to drag and drop the items from right to left and back?

**Comment by balachuang** [comment]
I'll test this problem and fix it.

**Comment by balachuang** [comment]
The bug of multiple elements is fixed.
